version: '3.8'
services:
  fogdb:
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_DATABASE=fog
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - '4000:3306'
    volumes:
      - fogdb:/var/lib/mysql
      - ./database/scripts/structure_data:/docker-entrypoint-initdb.d
  fogweb:
    depends_on:
      - fogdb
    build:
      context: .
      dockerfile: Dockerfile-fogweb
    image: tomcat
    environment:
      - DEPLOYED=$DEPLOYED
      - JDBC_USER=$JDBC_USER
      - JDBC_PASSWORD=$JDBC_PASSWORD
      - JDBC_DRIVER_PREFIX=$JDBC_DRIVER_PREFIX
      - JDBC_HOST=$JDBC_HOST
      - JDBC_DB=$JDBC_DB
      - JDBC_PARAMS=$JDBC_PARAMS
    ports:
      - '4100:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
volumes:
  fogdb:
    driver: local