name: GitHub Actions Fog Main
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H:%M:%S')"
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
        script: |
          cd sourcecode-pipeline
          mkdir CPH-Fog-Project-Semester2-${{ steps.date.outputs.date }}
          cd CPH-Fog-Project-Semester2-${{ steps.date.outputs.date }}
          git clone https://github.com/AbdullahMarwan/CPH-Fog-Project-Semester2.git &
          . ../../../sourcecode/SetEnv.sh 6
          echo "WARNING: Starting nuking of docker data, images, containers, volumes, networks. :"; docker rm -f -v $(docker ps -aq); docker rmi -f $(docker images -q); docker volume rm $(docker volume ls -q); docker network rm $(docker network ls -q); &
          docker compose down && docker compose build --no-cache && docker compose up -d &
          wait
